# NOTE: All files being used in this program are assumed to be in the same directory with this script,should you have your files elsewhere , you'll need to add the full file path.

# Required packages for Excel reading + XML handling
packages <- c("readxl", "xml2", "dplyr","httr","jsonlite") 

for(p in packages){
  # Try to load the package to see if installed 
  if(!require(p, character.only = TRUE)){ 
    install.packages(p)  # install package only if unavailable
    library(p, character.only = TRUE)  # load package after installing
  }
}

# -----------------------------
# 1.Read the source of literal questions (assuming this is an ODK xlsx form , read the survey sheet;making sure var_name maps to column "name" and literal_question maps to column "label")
# -----------------------------
survey_data <- read_excel(
  "Dummy-study-CHOLERA_MW_2024_Questionnaire_ODK.xlsx",# add what applies in your case 
  sheet = "survey"
)


survey_questions <- survey_data %>%
  select(name, label) %>%
  filter(!is.na(name), !is.na(label))

survey_questions$name <- trimws(tolower(survey_questions$name))

# -----------------------------
# 2. Read XML generated by Metadata Editor 
# -----------------------------
ddi_xml <- read_xml("Demo_Cholera.xml")# add your xml file here 

# Detect XML namespaces to prevent XML namespace look-up failure.
ns <- xml_ns(ddi_xml)
prefix <- names(ns)[1]

# -----------------------------
# 3. Find vars(variables) 
# -----------------------------
vars <- xml_find_all(ddi_xml, paste0(".//", prefix, ":var"), ns)

cat("Vars found:", length(vars), "\n")

updated_count <- 0

# -----------------------------
# 4. Loop through variables
# -----------------------------
for (v in vars) {
  
  var_name <- xml_attr(v, "name")
  
  if (!is.na(var_name)) {
    
    var_name_clean <- trimws(tolower(var_name))
    
    question_match <- survey_questions %>%
      filter(name == var_name_clean)
    
    if (nrow(question_match) == 1) {
      
      literal_question <- question_match$label
      
      # remove any existing qstn  (to avoid wrong placement)
      old_qstn <- xml_find_first(v, paste0("./", prefix, ":qstn"), ns)
      if (!is.na(old_qstn)) {
        xml_remove(old_qstn)
      }
      
      # find labl node
      labl_node <- xml_find_first(v, paste0("./", prefix, ":labl"), ns)
      
      if (!is.na(labl_node)) {
        
        # create qstn node
        qstn_node <- xml_add_sibling(labl_node, "qstn", .where = "after")
        
        # add qstnLit inside it
        xml_add_child(qstn_node, "qstnLit", literal_question)
        
        updated_count <- updated_count + 1
      }
    }
  }
}

# -----------------------------
# 5. Export the XML for importing into Metadata Editor [without pre/post question texts]
# -----------------------------
write_xml(ddi_xml, "Demo_Cholera_filled.xml") # add what applies in your case 

cat("Vars updated:", updated_count, "\n")


# ===========================================================================
# New things added to  v1.1: AI Hint Classification into preQTxt / postQTxt[literal questions with pre/post question texts]
# ---------------------------------------------------------------------------
#- Reads the hint and uses free Ollama locally installed model called 'gemma3' to classify whether the hint is pre/post literal question text 
#
# REQUIREMENT(S): 
#   - Install Ollama making sure you have atleast 8GB RAM 
#   - In the terminal  run gemma3 prior to using it in this script 
# ===========================================================================

# Keep only rows that have both a variable name AND a non-empty hint
survey_hints <- survey_data%>%
  select(name, hint) %>%
  filter(!is.na(name), !is.na(hint), trimws(hint) != "") %>%
  mutate(name = trimws(tolower(name)))

cat("\nHints found in ODK form:", nrow(survey_hints), "\n")

# ---- 6. AI classification helper (Ollama) ------------------------------------------
# opted for Ollama flash  because it's free 
classify_hint <- function(hint_text, api_key = NULL) { # no need for an API key for Ollama 
  
  prompt <- paste0(
    "You are a DDI (Data Documentation Initiative) metadata expert.\n",
    "Classify the following survey hint as EITHER:\n",
    "  preQTxt  — text shown BEFORE the question is asked ",
    "(e.g. eligibility conditions, context, interviewer instructions that apply before asking)\n",
    "  postQTxt — text shown AFTER the question is answered ",
    "(e.g. skip/routing logic, actions to take depending on the answer)\n\n",
    "Reply with ONLY the single word: preQTxt  or  postQTxt\n\n",
    "Hint text: \"", hint_text, "\""
  )
  
  response <- tryCatch({
    POST(
      url  = "http://localhost:11434/api/generate",
      add_headers("Content-Type" = "application/json"),
      body = toJSON(list(
        model  = "gemma3",
        prompt = prompt,
        stream = FALSE
      ), auto_unbox = TRUE),
      encode = "json"
    )
  }, error = function(e) {
    message("  [API ERROR] ", conditionMessage(e))
    return(NULL)
  })
  
  if (is.null(response)) return(NA_character_)
  
  if (status_code(response) != 200) {
    message("  [HTTP ", status_code(response), "] ", content(response, "text", encoding = "UTF-8"))
    return(NA_character_)
  }
  
  result_text <- tryCatch({
    parsed <- content(response, "parsed", encoding = "UTF-8")
    trimws(parsed$response)
  }, error = function(e) NA_character_)
  
  if (grepl("preQTxt",  result_text, ignore.case = TRUE)) return("preQTxt")
  if (grepl("postQTxt", result_text, ignore.case = TRUE)) return("postQTxt")
  
  message("  [WARN] Unexpected response: '", result_text, "'. Defaulting to preQTxt.")
  return("preQTxt")
}


# ---- 7. Re-read the exported XML 
ddi_xml2 <- read_xml("Demo_Cholera_filled.xml")
ns2      <- xml_ns(ddi_xml2)
prefix2  <- names(ns2)[1]

vars2 <- xml_find_all(ddi_xml2, paste0(".//", prefix2, ":var"), ns2)

hint_count <- 0

# ---- 10. Loop: classify each hint and inject into the correct node --------
for (v in vars2) {
  
  var_name <- xml_attr(v, "name")
  if (is.na(var_name)) next
  
  var_name_clean <- trimws(tolower(var_name))
  
  hint_match <- survey_hints %>% filter(name == var_name_clean)
  if (nrow(hint_match) != 1) next          
  
  hint_text <- trimws(hint_match$hint)
  
  cat("  Classifying hint for [", var_name, "]: ", hint_text, "\n", sep = "")
  
  node_type <- classify_hint(hint_text, api_key)   # "preQTxt" or "postQTxt"
  
  if (is.na(node_type)) {
    message("  [SKIP] Could not classify hint for variable: ", var_name)
    next
  }
  
  cat("    → classified as:", node_type, "\n")
  
  # Find the qstn node
  qstn_node <- xml_find_first(v, paste0("./", prefix2, ":qstn"), ns2)
  
  if (is.na(qstn_node)) {
    labl_node2 <- xml_find_first(v, paste0("./", prefix2, ":labl"), ns2)
    if (!is.na(labl_node2)) {
      qstn_node <- xml_add_sibling(labl_node2, "qstn", .where = "after")
    } else {
      message("  [SKIP] No <labl> or <qstn> node for variable: ", var_name)
      next
    }
  }
  
  # Remove any previously injected preQTxt / postQTxt to avoid duplicates
  for (old_tag in c("preQTxt", "postQTxt")) {
    old_node <- xml_find_first(qstn_node, old_tag)   
    if (!is.na(old_node)) xml_remove(old_node)
  }
  
  # Insert <preQTxt> or <postQTxt> as the FIRST or LAST child of <qstn>
  if (node_type == "preQTxt") {
    # preQTxt goes BEFORE qstnLit — insert as first child
    qstn_lit <- xml_find_first(qstn_node, "qstnLit")
    if (!is.na(qstn_lit)) {
      xml_add_sibling(qstn_lit, "preQTxt", hint_text, .where = "before")
    } else {
      xml_add_child(qstn_node, "preQTxt", hint_text, .where = 0)
    }
  } else {
    # postQTxt goes AFTER qstnLit — append as last child
    xml_add_child(qstn_node, "postQTxt", hint_text)
  }
  
  hint_count <- hint_count + 1
}

# ---- 11. Export the  XML with hints ------------------------------------
write_xml(ddi_xml2, "Demo_Cholera_filled_with_hints.xml")   

cat("\nHints classified and injected:", hint_count, "\n")
cat("Final output written to: Demo_Cholera_filled_with_hints.xml \n")
